# elp2000.pyi

from typing import Tuple

def geocentric_moon_position(t: float) -> Tuple[float, float, float]: ...
def geocentric_moon_position_of_date(t: float) -> Tuple[float, float, float]: ...
def geocentric_moon_position_cartesian(t: float) -> Tuple[float, float, float]: ...
def geocentric_moon_position_of_J2000(t: float) -> Tuple[float, float, float]: ...
def geocentric_moon_position_of_FK5(t: float) -> Tuple[float, float, float]: ...
