"""Dump Python-oracle values at the reference eclipses for the C++ parity tests.

Writes ``tests/cpp/fixtures/*.txt`` (roadmap §4, "Parity harness"): plain
whitespace-separated records so the Catch2 tests need no JSON library and run
without Python in the loop.  Regenerate after any *intended* change to the
oracle (``uv run python tools/dump_oracle.py``) and commit the result; the
diff is then the review record of what moved.

Record types::

    eop  <mjd> <xp_arcsec> <yp_arcsec> <dut1_s>            # eop_subset.txt
    case <label> <frame> <et> x y z d mu l1 l2 tan_f1 tan_f2 tt2 ut1 xp yp lon lat
    utc  <string> <et> <round_trip_string>

Numbers are written with ``repr`` (shortest round-trip), so the fixture holds
the oracle's doubles exactly.  The fixtures pin the **NAIF DE440s** kernel set
(header line); the C++ test skips when that SPK is not the one on disk.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import ephemeris as ep  # noqa: E402
from app import native  # noqa: E402
from app.eop import _table  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / "cpp" / "fixtures"
SPK = "de440s.bsp"

# label, UTC start, UTC end, samples: ±3 h around greatest eclipse, 13 samples
# (the pytest parity test uses 241; the fixture is a compact pin).
ECLIPSES = [
    ("se2017aug21", "2017-08-21T15:26:40", "2017-08-21T21:26:40"),
    ("se2023oct14", "2023-10-14T15:00:41", "2023-10-14T21:00:41"),
    ("se2024apr08", "2024-04-08T15:17:20", "2024-04-08T21:17:20"),
    ("se1919may29", "1919-05-29T10:08:00", "1919-05-29T16:08:00"),  # outside the IERS era
]
FRAMES = ("ITRS", "TOD", "ITRF93", "IAU_EARTH")
N = 13

UTC_CASES = [
    "2017-08-21T18:26:40",
    "2023-10-14T18:00:41.5",
    "2024-04-08T18:17:20",
    "2016-12-31T23:59:60",  # leap second
    "1919-05-29T13:08:00",  # pre-IERS: read as UT1 + model delta-T
    "2200-01-01T00:00:00",  # post-table: same rule
]


def header(fh, title: str) -> None:
    fh.write(f"# {title}\n# generated by tools/dump_oracle.py; do not edit, regenerate\n")
    fh.write(f"spk {SPK}\n")


def main() -> None:
    assert not native.is_native(), "dump the *Python* oracle: unset ECLIPSE_BACKEND"
    if not (ROOT / "kernels" / SPK).exists():
        sys.exit(f"fixtures pin {SPK}: run `python -m kernels.bootstrap --source naif`")
    ep.load_kernels()
    OUT.mkdir(parents=True, exist_ok=True)

    mjd, xp, yp, dut1 = _table()
    keep = np.zeros(len(mjd), dtype=bool)

    for label, utc0, utc1 in ECLIPSES:
        et = np.linspace(ep.utc_to_et(utc0), ep.utc_to_et(utc1), N)
        tt2, ut1, pxp, pyp = ep.earth_rotation_times(et)
        mjd_utc = ep._J2000_JD - ep._MJD_OFFSET + tt2  # ~UTC to a minute; ±5 d window
        for m in mjd_utc:
            keep |= np.abs(mjd - m) <= 5.0
        with open(OUT / f"{label}.txt", "w") as fh:
            header(fh, f"{label}: oracle Besselian elements, {utc0} .. {utc1}, {N} samples")
            for frame in FRAMES:
                try:
                    e = ep.besselian_instants(et, frame)
                    lon, lat = ep.sub_solar_points(et, frame)
                except Exception as exc:  # ITRF93 PCK has no 1919 coverage
                    fh.write(f"# {frame}: skipped ({type(exc).__name__})\n")
                    continue
                for i in range(N):
                    vals = [et[i], e["x"][i], e["y"][i], e["z"][i], e["d"][i], e["mu"][i],
                            e["l1"][i], e["l2"][i], e["tan_f1"][i], e["tan_f2"][i],
                            tt2[i], ut1[i], pxp[i], pyp[i], lon[i], lat[i]]
                    row = " ".join(repr(float(v)) for v in vals)
                    fh.write(f"case {label}[{i}] {frame} {row}\n")

    with open(OUT / "utc_cases.txt", "w") as fh:
        header(fh, "utc_to_et / et_to_utc oracle cases (IERS-era rule)")
        for s in UTC_CASES:
            et = ep.utc_to_et(s)
            keep |= np.abs(mjd - (ep._J2000_JD - ep._MJD_OFFSET + et / 86400.0)) <= 5.0
            fh.write(f"utc {s} {et!r} {ep.et_to_utc(et)}\n")

    with open(OUT / "eop_subset.txt", "w") as fh:
        header(fh, "IERS Bulletin A rows (astropy-iers-data) within 5 d of the cases")
        for i in np.flatnonzero(keep):
            cols = " ".join(repr(float(v)) for v in (mjd[i], xp[i], yp[i], dut1[i]))
            fh.write(f"eop {cols}\n")
    n_rows = int(keep.sum())
    print(f"wrote {len(ECLIPSES) + 2} fixtures to {OUT.relative_to(ROOT)}, {n_rows} EOP rows")


if __name__ == "__main__":
    main()
